name: Common CI

on:
  push:
    branches:
      - main

jobs:
  backend-task:
    uses: ShunSakakida/common-ci/.github/workflows/common-ci.yml@main
    with:
      message: "This is a message from the backend repo"